// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKQEtBoLEC5KCkVbvc7I2AD8Zn_DxxYQ4',
    appId: '1:676492421851:web:0a6ef42883d085ffbdbafe',
    messagingSenderId: '676492421851',
    projectId: 'expense-tracker-7e96a',
    authDomain: 'expense-tracker-7e96a.firebaseapp.com',
    storageBucket: 'expense-tracker-7e96a.firebasestorage.app',
    measurementId: 'G-0S2CGRSWT5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiOGALr-0vMSBr74Q8KSGdGCoaPe_WH0I',
    appId: '1:676492421851:android:01c3a55c52ab45bebdbafe',
    messagingSenderId: '676492421851',
    projectId: 'expense-tracker-7e96a',
    storageBucket: 'expense-tracker-7e96a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCzdPlKnvwX9AGOP-SgI7s9NevU5MkgAA',
    appId: '1:676492421851:ios:5b52e64d6bd027e3bdbafe',
    messagingSenderId: '676492421851',
    projectId: 'expense-tracker-7e96a',
    storageBucket: 'expense-tracker-7e96a.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCzdPlKnvwX9AGOP-SgI7s9NevU5MkgAA',
    appId: '1:676492421851:ios:5b52e64d6bd027e3bdbafe',
    messagingSenderId: '676492421851',
    projectId: 'expense-tracker-7e96a',
    storageBucket: 'expense-tracker-7e96a.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKQEtBoLEC5KCkVbvc7I2AD8Zn_DxxYQ4',
    appId: '1:676492421851:web:f60e0f0018ee6a9bbdbafe',
    messagingSenderId: '676492421851',
    projectId: 'expense-tracker-7e96a',
    authDomain: 'expense-tracker-7e96a.firebaseapp.com',
    storageBucket: 'expense-tracker-7e96a.firebasestorage.app',
    measurementId: 'G-VZRDGF3DHE',
  );
}
